# -*- coding: utf-8 -*-
"""prediksi kelulusan tepat waktu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18JcSkT3zak5x9fa6X5FF_x93ZSwGGPSG
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Load model yang sudah kamu simpan sebelumnya
model = joblib.load('best_model.pkl')  # Simpan model di tahap training: joblib.dump(grid_search.best_estimator_, 'best_model.pkl')

# Judul aplikasi
st.title("Prediksi Kelulusan Tepat Waktu")

# Form input data mahasiswa
st.header("Masukkan Data Mahasiswa")

# Contoh fitur, sesuaikan dengan fitur dataset kamu
ipk = st.number_input("IPK", min_value=0.0, max_value=4.0, step=0.01)
lama_studi = st.number_input("Lama Studi (semester)", min_value=0, step=1)
jumlah_matkul_tidak_lulus = st.number_input("Jumlah Mata Kuliah Tidak Lulus", min_value=0, step=1)
kehadiran = st.number_input("Persentase Kehadiran (%)", min_value=0, max_value=100, step=1)

# Tombol prediksi
if st.button("Prediksi"):
    # Buat dataframe dari input
    input_data = pd.DataFrame({
        'IPK': [ipk],
        'Lama Studi': [lama_studi],
        'Jumlah Mata Kuliah Tidak Lulus': [jumlah_matkul_tidak_lulus],
        'Kehadiran': [kehadiran]
    })

    # Prediksi
    prediksi = model.predict(input_data)[0]
    probabilitas = model.predict_proba(input_data)[0]

    # Tampilkan hasil
    if prediksi == 1:
        st.success(f"Prediksi: Lulus Tepat Waktu ({probabilitas[1]:.2%} keyakinan)")
    else:
        st.error(f"Prediksi: Tidak Lulus Tepat Waktu ({probabilitas[0]:.2%} keyakinan)")

